blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/atakan72/iconmanager/security/advisories/new
    about: Please report security vulnerabilities via private advisory.
